"" Pascal Mehnert
"" Version: 1 billion 


set nocompatible
set encoding=utf-8
packadd! matchit
set backupext=.bak

"" General
set ruler                       " Show row and column ruler information
set number                      " Show line numbers
set listchars=tab:>-,trail:-    " Show tabs as >--- and trailing spaces as -
set linebreak                   " Break lines at work
set showbreak=+++               " Wrap-broken line prefix
set textwidth=120               " Line wrap (after cols)
set showmatch                   " Highlight matching braces
set cmdheight=1                 " Number of lines at bottom of screen
set tw=0                        " Don't use automatic line breaks
set backspace=indent,eol,start  " Set the backspace to delete by default
syntax enable                   " Enable syntax highlighting

"" Indentation
if has('autocmd')
    filetype plugin indent on
endif

set smarttab
set tabstop=4                   " Number of hard-tabstop spaces
set shiftwidth=4                " Number of auto-indent spaces
set expandtab                   " Use spaces instead of tabs
set autoindent

"" Folding
set foldmethod=manual

"" Misc key mappings

"" Configure split behaviour
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set splitbelow
set splitright

"" Configure tab behaviour
map <C-N> :tabp<CR>
map <C-M> :tabn<CR>

"" Airline Configuration
set laststatus=2                                    " Always show status bar
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme = 'luna'

let g:airline#extensions#whitespace#enabled = 0
"let g:airline#extensions#vimtex#enabled = 1

"" Vimtex Configuration
let g:vimtex_compiler_method = 'latexmk'
" let g:vimtex_compiler_latexmk = {'build_dir' : './latexmk_out/'}
let g:vimtex_complete_close_braces = 1
let g:vimtex_fold_enabled = 1
let g:vimtex_fold_comments = 1

let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'

"" Skeleton configuration
let skeletons#autoRegister= 1
let skeletons#skeletonsDir=['~/.vim/skeletons','/etc/vim/skeletons']

"" ultisnips configuration
let g:UltiSnipsExpandTrigger='<C-J>'
let g:UltiSnipsJumpForwardTrigger='<C-L>'
let g:UltiSnipsJumpBackwardTrigger='<C-H>'

" let g:UltiSnipsSnippetsDir='~/.vim/snippets/UltiSnips'
let g:UltiSnipsSnippetDirectories=["UltiSnips"]

"" ycm (you complete me) configuration
let g:ycm_global_ycm_extra_conf='/usr/share/vim/vimfiles/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
" let g:ycm_server_python_interpreter='/bin/python2'

let g:ycm_python_binary_path = '/usr/bin/python3'

"" File Type options
autocmd BufNewFile,BufReadPost *.md,*.mkd set filetype=markdown
let g:markdown_fenced_languages = ['javascript', 'go', 'php']

autocmd BufNewFile,BufReadPost *.asm set filetype=mips
autocmd BufNewFile,BufReadPost *.coffee set filetype=coffee

"" Plugins
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'

    Plugin 'junegunn/goyo.vim'
    Plugin 'junegunn/vim-easy-align'

    Plugin 'tpope/vim-surround'
    Plugin 'tpope/vim-fugitive'

    Plugin 'vim-airline/vim-airline'
    Plugin 'vim-airline/vim-airline-themes'
    
    Plugin 'SirVer/ultisnips'
    Plugin 'honza/vim-snippets'
    Plugin 'pgilad/vim-skeletons'
    Plugin 'davidhalter/jedi-vim'

    Plugin 'scrooloose/nerdtree'
    Plugin 'ap/vim-css-color'
    Plugin 'lervag/vimtex'

    Plugin 'harenome/vim-mipssyntax'
    Plugin 'vim-syntastic/syntastic'

    Plugin 'tmhedberg/SimpylFold'
    Plugin 'Konfekt/FastFold'

    Plugin 'Valloric/YouCompleteMe'
    Plugin 'rdnetto/YCM-Generator'
    Plugin 'freitass/todo.txt-vim'
call vundle#end()
