#!/usr/bin/python

import sys
import os
from task import TaskFile

todo_sh = os.environ['TODO_SH']
todo_full_sh = os.environ['TODO_FULL_SH']
todo_dir = os.environ['TODO_DIR']
todo_file = os.environ['TODO_FILE']

usage = "%s sort" % todo_sh

help_msg = """ sort:
    sort
      Sorts the todo.txt file. Sorts the tasks by priority.
      Tasks with the same priority are sorted using their description.
      If a task has no priority, it will be put at the end of the file.
      Empty lines will be delted.
"""

if sys.argv[1] == "usage":
    print(help_msg)
    sys.exit()

with TaskFile(todo_file) as task_file:
    print("TODO: Sorted todo.txt file at '%s'" % todo_file)
    task_file.sort()
