# ~/.zshenv

export ZDOTDIR="$HOME"

export TERM="screen-256color"

export EDITOR=/usr/bin/nvim
export VISUAL=/usr/bin/nvim
export GRAPHICAL=/usr/bin/gvim

export PAGER=/usr/bin/vimpager
export PDFVIEW=/usr/bin/evince

export LANG=en_US.UTF-8

if [ -n "$DISPLAY" ]; then
    export BROWSER=/usr/bin/firefox
else
    export BROWSER=/usr/bin/links
fi
