#
# ~/.zshrc
#

zstyle ':completion:*' completer _expand _complete _approximate _ignored _correct
zstyle ':completion:*' expand suffix
zstyle ':completion:*' format 'Complete %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' insert-unambiguous false
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=* r:|=*'
zstyle ':completion:*' menu select=0
zstyle ':completion:*' original true
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' verbose true
zstyle ':completion:*' rehash true
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit promptinit
compinit
promptinit

HISTFILE=~/.zsh-history
HISTSIZE=2000
SAVEHIST=2000

setopt appendhistory autocd extendedglob notify
unsetopt beep nomatch
bindkey -v

# Enable git completion
zstyle ':completion:*:*:git:*' script /usr/share/git/completion/git-completion.zsh

setopt PROMPT_SUBST

export ZSH=~/.oh-my-zsh
export UPDATE_ZSH_DAYS=7

ZSH_THEME='powerlevel9k/powerlevel9k'
plugins=(extract git thefuck vi-mode vundle wd zsh-syntax-highlighting zsh_reload rsync tmux systemd)

# Disable powerlevel9k if in virtual console 
if [[ "$TERM" == "linux" ]]; then
    unset ZSH_THEME
fi

# Configure Powerlevel9k  # TODO
DEFAULT_FOREGROUND=240
DEFAULT_BACKGROUND='white'
DEFAULT_COLOR=$DEFAULT_FOREGROUND

POWERLEVEL9K_MODE='nerdfont-complete'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='╭─'
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='╰%F{blue}\uf105\uf105\uf105%f '

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time root_indicator background_jobs battery ssh time)

# Configure os_icon segment
POWERLEVEL9K_OS_ICON_BACKGROUND='white'
POWERLEVEL9K_OS_ICON_FOREGROUND='blue'
POWERLEVEL9K_LINUX_ICON='\uf300'

# Configure dir segment
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
POWERLEVEL9K_DIR_SUBFOLDER_FOREGROUND='white'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'

# Configure status segment
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_HIDE_SIGNAME=true

# Configure command_execution_time segment
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5

# Configure battery segment
POWERLEVEL9K_BATTERY_VERBOSE=false
POWERLEVEL9K_BATTERY_ICON=''
POWERLEVEL9K_BATTERY_LOW_BACKGROUND='red'
POWERLEVEL9K_BATTERY_LOW_FOREGROUND='white'
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='yellow'
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='white'
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='green'
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='white'
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='blue'
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND='white'

# Configure time segment
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M} \uF017'
POWERLEVEL9K_TIME_BACKGROUND='240'
POWERLEVEL9K_TIME_FOREGROUND='white'

# Configure zsh-syntax-highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

source $ZSH/oh-my-zsh.sh

# Enable zsh syntax highlighting
if [[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then 
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# Source global alias definitions from /etc/zsh/zsh_aliases
if [[ -f /etc/zsh/zsh-aliases ]]; then
    source /etc/zsh/zsh-aliases
fi

# Source user specific alias definitions from ~/.zsh_aliases
if [[ -f ~/.zsh-aliases ]]; then
    source ~/.zsh-aliases
fi

# Source ssh session specific alias definition from ~/.zsh_aliases.ssh
if [[ -n "$SESSION_TPE" ]] && [[ -f ~/.zsh-aliases.ssh ]]; then
    source ~/.zsh-aliases.ssh
fi

# Source user specific functions from ~/.zsh_functions
if [[ -f ~/.zsh-functions ]]; then
    source ~/.zsh-functions
fi

# Start the ssh-agent if it is not already running
# !! IMPORTANT: Add "AddKeysToAgent yes" to ~/.ssh/config !!
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
fi

if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-thing)" > /dev/null
fi
