#
# /etc/zsh/zshrc
#

# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' expand suffix
zstyle ':completion:*' format 'Complete %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' insert-unambiguous false
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=* r:|=*'
zstyle ':completion:*' menu select=0
zstyle ':completion:*' original true
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/etc/zsh/zshrc'

autoload -Uz compinit promptinit
compinit
promptinit
# End of lines added by compinstall

# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob notify
unsetopt beep nomatch
bindkey -v
# End of lines configured by zsh-newuser-install

# Enable git completion
zstyle ':completion:*:*:git:*' script /usr/share/git/completion/git-completion.zsh

setopt PROMPT_SUBST

# Set left prompt
PROMPT="[%n@%m %1~]%# "

# Enable and configure git prompt as right prompt
if [ -f /usr/share/git/completion/git-prompt.sh ]; then
    source /usr/share/git/completion/git-prompt.sh
    RPROMPT='$(__git_ps1 "[%s]")'

    # Indicate (un)staged changes (+ and *)
    GIT_PS1_SHOWDIRTYSTATE=true

    # Indicate untracked files (%)
    GIT_PS1_SHOWUNTRACKEDFILES=true

    # Indicate difference between HEAD and its upstream
    GIT_PS1_SHOWUPSTREAM="auto"

    # Use colors for hints
    GIT_PS1_SHOWCOLORHINTS=true  # Todo: Not working as of right now
fi

# Source global alias definitions from /etc/zsh/zsh_aliases
[ -f /etc/zsh/zsh_aliases ] && source /etc/zsh/zsh_aliases

# Source user specific alias definitions from ~/.zsh_aliases
[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases

# Start the ssh-agent if it is not already running
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
fi

if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-thing)"
fi
