#
# /etc/bash.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -f /usr/share/git/completion/git-prompt.sh ]; then
    source /usr/share/git/completion/git-prompt.sh
    PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
else
    echo "Can't find git-completion.bash"
    PS1='[\u@\h \W]\$ '
fi

# Enable git completion
if [[ -f /usr/share/git/completion/git-completion.bash ]]; then
    source /usr/share/git/completion/git-completion.bash
fi

# Enable maven completion (github.com/juven/maven-bash-completion)
if [[ -f /etc/maven-bash-completion.bash ]]; then
    source /etc/maven-bash-completion.bash
fi

# Start the ssh-agent if it is not already running
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
fi

if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-thing)"
fi

export VISUAL=vim
export GRAPHICAL=gvim
export PDFVIEW=okular

# Source global alias definitions from /etc/bash.bash_aliases
if [[ -f /etc/bash.bash-aliases ]]; then
    source /etc/bash.bash-aliases
fi

# Source alias definitions from ~/.bash_alias
if [[ -f ~/.bash_aliases ]]; then
    source ~/.bash_aliases
fi
