#
# /etc/bash.bashrc
#

shopt -s autocd

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source gloabal envrionment variables
if [[ -f /etc/bash.bashenv ]]; then
    source /etc/bash.bashenv
fi

# Source envrionment variables
if [[ -f ~/.bashenv ]]; then
    source ~/.bashenv
fi

# Source global alias definitions from /etc/bash.bash-aliases
if [[ -f /etc/bash.bash-aliases ]]; then
    source /etc/bash.bash-aliases
fi

# Source alias definitions from ~/.bash-aliases
if [[ -f ~/.bash-aliases ]]; then
    source ~/.bash-aliases
fi


# Source ssh session specific alias definition from ~/.bash_aliases.ssh
if [[ -n "$SESSION_TPE" ]] && [[ -f ~/.zsh-aliases.ssh ]]; then
    source ~/.zsh-aliases.ssh
fi
    
# Try sourcing the git prompt 
if [ -f /usr/share/git/completion/git-prompt.sh ]; then
    source /usr/share/git/completion/git-prompt.sh
    PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
else
    echo "Can't find git-completion.bash"
    PS1='[\u@\h \W]\$ '
fi

# Enable bash comletion
if [[ -f /usr/share/bash-completion/bash_completion ]]; then
    source /usr/share/bash-completion/bash_completion
fi

# Enable git completion
if [[ -f /usr/share/git/completion/git-completion.bash ]]; then
    source /usr/share/git/completion/git-completion.bash
fi

# Enable maven completion (github.com/juven/maven-bash-completion)
if [[ -f /etc/maven-bash-completion.bash ]]; then
    source /etc/maven-bash-completion.bash
fi

# Start the ssh-agent if it is not already running
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
fi

if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-thing)"
fi
